### ISSUE TITLE
Failure building heap.js

### ISSUE THREAD

**Issue by kumavis** [js-js/heap.js#1]
```
╭─{🎩 } kumavis in ~/Development/Node/js.js on (master✱) 
╰─± npm i
npm WARN package.json jit.js@0.8.23 No repository field.

> mmap.js@0.2.1 install /Users/kumavis/Development/Node/js.js/node_modules/heap.js/node_modules/mmap.js
> node-gyp rebuild

  CXX(target) Release/obj.target/mmap/src/mmap.o
  SOLINK_MODULE(target) Release/mmap.node
  SOLINK_MODULE(target) Release/mmap.node: Finished

> heap.js@0.23.2 install /Users/kumavis/Development/Node/js.js/node_modules/heap.js
> node-gyp rebuild

  CXX(target) Release/obj.target/heap/src/heap.o
../src/heap.cc:392:58: warning: expression which evaluates to zero treated as a null pointer constant of type 'NanFunctionCallback'
      (aka 'Handle<v8::Value> (*)(const v8::Arguments &)') [-Wnon-literal-null-conversion]
  target->Set(NanNew("tagSmi"), NanNew<Number, uint32_t>(kTagSmi));
                                                         ^~~~~~~
In file included from ../src/heap.cc:1:
In file included from ../node_modules/nan/nan.h:74:
../node_modules/nan/nan_new.h:249:49: error: too many arguments to function call, expected single argument 'value', have 3 arguments
    return NanIntern::Factory<T>::New(callback, data, a2);
           ~~~~~~~~~~~~~~~~~~~~~~~~~~           ^~~~~~~~
../src/heap.cc:392:33: note: in instantiation of function template specialization 'NanNew<v8::Number, unsigned int>' requested here
  target->Set(NanNew("tagSmi"), NanNew<Number, uint32_t>(kTagSmi));
                                ^
../node_modules/nan/nan_implementation_pre_12_inl.h:109:1: note: 'New' declared here
Factory<v8::Number>::return_t
^
1 warning and 1 error generated.
make: *** [Release/obj.target/heap/src/heap.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kumavis/Development/Node/js.js/node_modules/heap.js
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/share/npm/bin/npm" "i"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! heap.js@0.23.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the heap.js@0.23.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the heap.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls heap.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kumavis/Development/Node/js.js/npm-debug.log
```

**Comment by indutny** [comment]
Should be fixed in next io.js release with heap.js@1.0.0 . See https://github.com/iojs/io.js/pull/1375
